name: Terraform Dev

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-dev.yml"

  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-dev.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-dev
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials using GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::861019856428:role/devops-cicd-github-actions-role
          aws-region: eu-west-2
          role-session-name: github-actions-terraform-dev
          allowed-account-ids: "861019856428"

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.1"
          terraform_wrapper: false

      - name: Terraform version
        run: terraform version

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform plan summary
        run: terraform show -no-color tfplan
